### ISSUE TITLE
Increase default 3D panel size

### ISSUE THREAD

**Issue by richford** [yeatmanlab/AFQ-Browser#168]

**Comment by akeshavan** [comment]
For PR #176 @arokem @jyeatman @anotherjoshsmith what do you think of this new layout? The major changes are:

1) made padding around titles/text smaller so that I could make windows larger (specifically, the 3D window)
2) removed gray background - I think the dashed lines are enough to separate the different canvases
3) added subtitles to each canvas @richford thinks its a little crowded - in the future I can add a hide/show help button, but I think for first-time users it helps them know what to click

smaller UI changes include:
1) a pointer cursor on the table hover so you know to click it
2) larger margins on buttons, so you know its a button and not a label

<img width="1438" alt="screen shot 2017-11-02 at 3 07 43 pm" src="https://user-images.githubusercontent.com/972008/32352729-aeee6592-bfdf-11e7-9926-01ff3ae51111.png">

**Comment by richford** [comment]
Also add note to mobile browser users that AFQ-Browser is not supported on mobile platforms.

**Comment by richford** [comment]
You also mentioned using a three.js loadingManager
https://threejs.org/docs/#api/loaders/managers/LoadingManager
to show a loading animation.

Or better yet, use https://www.npmjs.com/package/loadscreen
with an example shown here: https://codepen.io/Astrak/pen/OpwEZj?editors=0010

**Comment by akeshavan** [comment]
@richford added a 700px breakpoint & a message saying to use desktop: https://github.com/yeatmanlab/AFQ-Browser/pull/176/commits/c83f0ae47fc11eadc09f72e22a9bf6e72dad0dcb

**Comment by richford** [comment]
Resolved by #176.
