### ISSUE TITLE
faPlotLength

### ISSUE THREAD

**Issue by arokem** [yeatmanlab/AFQ-Browser#184]
Currently, the variable `faPlotLength` holds the expected length of the plots of the metrics as one single number. However, in Tracula, different tracts may have different lengths. As an example, [this code](https://github.com/yeatmanlab/AFQ-Browser/blob/master/afqbrowser/site/client/js/3d-brain.js#L203-L226) checks that all the streamlines have that same length, so will need to be refactored to point to a list (?) of lengths.

**Comment by richford** [comment]
Currently we require that all fibers be the same length, but for starts there's no reason that it has to be `faPlotLength`. So #188 removes that dependence. But this doesn't necessarily solve this issue.

Tracula only has one central core fiber right? In that case, then #188 fixes this since each bundle is allowed to have a different length.

But for performance reasons and to make brushing easier to implement, it is really nice to require that each fiber in a bundle is the same length. So if we need to have multiple fibers of varying length within a single bundle, then I'll have to think more about how to implement this.

**Comment by arokem** [comment]
I think it's fine to assume that all the fibers within a bundle are resampled to have the same length, allowing for different bundles to have different lengths. That means #188 solves this, right?

**Comment by richford** [comment]
Yep. #188 should fix this. I still haven't implemented the differentiation between core fiber and other fibers. But #188 should fix this specific issue.

**Comment by richford** [comment]
Resolved by #188.
