### ISSUE TITLE
Infer the tract list from the nodes.csv table

### ISSUE THREAD

**Issue by arokem** [yeatmanlab/AFQ-Browser#49]
Instead of the currently hard-coded list: 

https://github.com/yeatmanlab/AFQ-Browser/blob/master/client/js/tract-details.js#L4

This might need to wait until after resolving #19

**Comment by richford** [comment]
This is also in 3d-brain.js so we should remove it there as well. Likewise, the colors are duplicated in 3d-brain.js and tract-details.js even though only `d3colors` is used in tract-details.js and only `colors` and `highlightColors` are used in 3d-brain.js. Lastly, `m`, `w`, and `h` are not used in 3d-brain.js and should be removed. So I suggest:
- [ ] Move, `tracts` into another js file (naming suggestions please)
- [ ] Read tract names from nodes.csv as @arokem suggests
- [ ] Also move all color variables into this common js file so that if we ever decide to change the colors, we don't have to hunt around different files to do so.
